# Generated by Django 5.2.6 on 2026-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social', models.IntegerField()),
            ],
        ),
    ]
